<div class='form-horizontal'>
	<div id="users-form-errors" class='alert alert-error' style="display:none;">
		<?php $errorMessages = $this->element->getMessages();
			  foreach($errorMessages as $field => $errors) {
			    echo sprintf("%s Errors: %s", $field, $this->formErrors($errors));
			} ?>
	</div>
	<div id="users-form-success" class='alert alert-success' style="display:none;">
		<p>Successfully Created User</p>
	</div>
	<form class="form-horizontal">
  		<fieldset>
    		<legend>Users Sign Up</legend>
    		<div class="control-group">
      			<label class="control-label" for="name">Name</label>
      			<div class="controls">
					<?php echo $this->element->getElement('name');?>
      			</div>
    		</div>
    		<div class="control-group">
      			<label class="control-label" for="email">E-Mail</label>
      			<div class="controls">
					<?php echo $this->element->getElement('email');?>
      			</div>
    		</div>
    		<div class="control-group">
      			<label class="control-label" for="password">Password</label>
      			<div class="controls">
					<?php echo $this->element->getElement('password');?>
      			</div>
    		</div>
			<div class="form-actions">
      			<?php echo $this->element->getElement('submit');?>
    		</div>
		</fieldset>
	</form>
</div>